repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: yarn format:staged
        language: node
        types_or: [javascript, jsx, ts, tsx, vue]
      - id: eslint
        name: eslint
        language: node
        types_or: [javascript, jsx, ts, tsx, vue]
        entry: yarn lint:staged
