[tool.isort]
profile = 'black'
src_paths = ['.']
skip = ['./__init__.py']

[tool.pylint.'MESSAGES CONTROL']
# Temporarily disabling trivial warnings
disable = 'invalid-name,missing-function-docstring,missing-class-docstring,missing-module-docstring,fixme,global-statement,import-outside-toplevel,protected-access,too-few-public-methods,too-many-ancestors,too-many-function-args,arguments-differ,cyclic-import'

[tool.pylint.'FORMAT']
max-line-length = 200
max-module-lines = 5500

[tool.pylint.'BASIC']
good-names = '_,e,i,j,k,x,y,z,ar,ex,rs,_AggregateRootType'

[tool.pylint.'DESIGN']
max-args = 35
max-attributes = 85
max-branches = 50
max-locals = 46
max-public-methods = 81
max-returns = 9
max-statements = 100

[tool.pylint.'REFACTORING']
max-nested-blocks = 10

[tool.pylint.'SIMILARITIES']
min-similarity-lines = 1000
